c_file="src/generated.h"
ts_file="frontend/src/lib/generated.ts"

# Define enums as associative arrays
BACKEND_TO_FRONTEND_KEYS="FRAME_START FRAME_END BOOTED SCORE BULLETS"

FRONTEND_TO_BACKEND_KEYS="BUTTON_PRESS"

# Define variables
VARIABLES_KEYS="SCREENX SCREENY BAUD BITS_PER_COLOR"
# screen size x must be multiple of 12
VARIABLES_VALUES="60 60 1000000 2"

# Function to generate C enum
generate_c_enum() {
    local enum_name="$1"
    local keys="$2"

    echo "typedef enum __attribute__((packed)) {" >> "$c_file"
    local key_array=($keys)
    for i in "${!key_array[@]}"; do
        echo "    ${key_array[$i]} = ${i}," >> "$c_file"
    done
    echo "} ${enum_name};" >> "$c_file"
    echo "" >> "$c_file"
}

# Function to generate TypeScript enum
generate_ts_enum() {
    local enum_name="$1"
    local keys="$2"

    echo "export enum ${enum_name} {" >> "$ts_file"
    local key_array=($keys)
    for i in "${!key_array[@]}"; do
        echo "    ${key_array[$i]} = ${i}," >> "$ts_file"
    done
    echo "}" >> "$ts_file"
    echo "" >> "$ts_file"
}

# Function to generate C defines
generate_c_defines() {
    local keys="$1"
    local values="$2"

    local key_array=($keys)
    local value_array=($values)
    for i in "${!key_array[@]}"; do
        echo "#define ${key_array[$i]} ${value_array[$i]}" >> "$c_file"
    done
    echo "" >> "$c_file"
}

# Function to generate TypeScript constants
generate_ts_constants() {
    local keys="$1"
    local values="$2"

    local key_array=($keys)
    local value_array=($values)
    for i in "${!key_array[@]}"; do
        echo "export const ${key_array[$i]} = ${value_array[$i]};" >> "$ts_file"
    done
    echo "" >> "$ts_file"
}

# Clear files
> "$c_file"
> "$ts_file"

# Generate C header
echo "// THIS FILE IS AUTOGENERATED FROM generate-types.sh" >> "$c_file"
echo "// DO NOT MODIFY MANUALLY" >> "$c_file"
echo "" >> "$c_file"
echo "#ifndef GENERATED_H" >> "$c_file"
echo "#define GENERATED_H" >> "$c_file"
echo "" >> "$c_file"
echo "#include <stdint.h>" >> "$c_file"
echo "" >> "$c_file"

# Generate C content
generate_c_defines "$VARIABLES_KEYS" "$VARIABLES_VALUES"
generate_c_enum "BACKEND_TO_FRONTEND" "$BACKEND_TO_FRONTEND_KEYS"
generate_c_enum "FRONTEND_TO_BACKEND" "$FRONTEND_TO_BACKEND_KEYS"

echo "#endif" >> "$c_file"

# Generate TypeScript content
echo "// THIS FILE IS AUTOGENERATED FROM generate-types.sh" >> "$ts_file"
echo "// DO NOT MODIFY MANUALLY" >> "$ts_file"
echo "" >> "$ts_file"
generate_ts_constants "$VARIABLES_KEYS" "$VARIABLES_VALUES"
generate_ts_enum "BACKEND_TO_FRONTEND" "$BACKEND_TO_FRONTEND_KEYS"
generate_ts_enum "FRONTEND_TO_BACKEND" "$FRONTEND_TO_BACKEND_KEYS"
