// THIS FILE IS AUTOGENERATED FROM generate-types.sh
// DO NOT MODIFY

#ifndef GENERATED_H
#define GENERATED_H

#include <stdint.h>

#define SCREENX 48
#define SCREENY 48
#define BAUD 1000000

typedef enum {
    FRAME_START,
    FRAME_END,
} BACKEND_TO_FRONTEND;

typedef enum {
    BUTTON_PRESS,
} FRONTEND_TO_BACKEND;

#endif
