// THIS FILE IS AUTOGENERATED FROM generate-types.sh
// DO NOT MODIFY MANUALLY

#ifndef GENERATED_H
#define GENERATED_H

#include <stdint.h>

#define SCREENX 24
#define SCREENY 24
#define BAUD 1000000
#define BITS_PER_COLOR 2

typedef enum __attribute__((packed)) {
    FRAME_START = 0,
    FRAME_END = 1,
    BOOTED = 2,
} BACKEND_TO_FRONTEND;

typedef enum __attribute__((packed)) {
    BUTTON_PRESS = 0,
} FRONTEND_TO_BACKEND;

#endif
