// THIS FILE IS AUTOGENERATED FROM generate-types.sh
// DO NOT MODIFY

export const SCREENX = 48;
export const SCREENY = 48;
export const BAUD = 1000000;

export enum BACKEND_TO_FRONTEND {
    FRAME_START,
    FRAME_END,
}

export enum FRONTEND_TO_BACKEND {
    BUTTON_PRESS,
}

