// THIS FILE IS AUTOGENERATED FROM generate-types.sh
// DO NOT MODIFY MANUALLY

export const SCREENX = 48;
export const SCREENY = 48;
export const BAUD = 1000000;
export const BITS_PER_COLOR = 2;

export enum BACKEND_TO_FRONTEND {
    FRAME_START = 0,
    FRAME_END = 1,
    BOOTED = 2,
}

export enum FRONTEND_TO_BACKEND {
    BUTTON_PRESS = 0,
}

